about/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('',AboutView.as_view(),name='about'),
]

blogapp/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('',BlogView.as_view(),name='blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls')),
    path('episodes/', include('episodes.urls')),
    path('', include('index.urls')),
    path('about/', include('about.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

episodes/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', EpisodesView.as_view(), name='episodes'),
    path('<int:pk>', EpisodeView.as_view(), name='episode'),
]

index/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('contact/',ContactView.as_view(),name='contact')
]

about/models.py
from django.db import models

# Create your models here.

blogapp/models.py
from django.db import models

# Create your models here.

episodes/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='images/users/')
    job = models.CharField(max_length=60)

    def __str__(self):
        return self.username


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    podcast = models.ForeignKey('Podcast', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Comments'
        verbose_name = 'Comment'


class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    podcast = models.ForeignKey('Podcast', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Likes'
        verbose_name = 'Like'


class Category(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category


class Tags(models.Model):
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag


class Podcast(models.Model):
    # autor = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created = models.DateField(auto_now_add=True)
    picture = models.ImageField(upload_to='images/podcasts/')
    file = models.FileField(upload_to='files/')
    about = models.TextField()
    guests = models.ManyToManyField(User, blank=True)
    category = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tags)

    def __str__(self):
        return self.title

index/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Contact(models.Model):
    name = models.CharField(verbose_name='Name', max_length=200)
    phone = models.CharField(verbose_name='Phone', max_length=40)
    subject = models.CharField(verbose_name='Subject', max_length=200)
    message = models.TextField()
    create = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('contact', self.pk)

    def __str__(self):
        return self.name


class Subscribe(models.Model):
    email = models.EmailField(verbose_name='Email', max_length=200)

    def __str__(self):
        return self.email

index/forms.py
from django.forms import ModelForm
from .models import Contact, Subscribe


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class SubscribeForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

about/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class AboutView(TemplateView):
    template_name = 'about.html'

blogapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class BlogView(TemplateView):
    template_name = 'blog.html'

episodes/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, ListView

from episodes.models import Podcast, Category, Tags


# Create your views here.

class EpisodesView(ListView):
    template_name = 'episodes.html'
    model = Podcast
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['tags'] = Tags.objects.all()
        return context


class EpisodeView(DetailView):
    template_name = 'episode.html'
    model = Podcast
    context_object_name = 'podcast'

index/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from .models import *
from .forms import *


# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'


class ContactView(CreateView):
    template_name = 'contact.html'
    model = Contact
    form_class = ContactForm

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/about.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css' %}">
{%  endblock links %}

{% block content %}

    <div class="home">
        <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/about.jpg' %}"
             data-speed="0.8" style="height: 400px"></div>
        <div class="home_container d-flex flex-column align-items-center justify-content-center">
            <div class="home_content">
                <div class="home_title"><h1>about</h1></div>
            </div>
        </div>
    </div>



    <div class="intro">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="intro_content text-center">
                        <div class="section_title text-center"><h1>About my<span>podcast</span></h1></div>
                        <div class="intro_text text-center">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a bibendum sem. Fusce
                                dignissim et diam quis pretium.
                                Etiam efficitur semper accumsan. Sed et dui aliquet, ultrices tellus non, sagittis
                                magna. Nullam justo quam, vestibulum non magna et, tempus tincidunt est. Ut laoreet
                                magna ac luctus lacinia. Aliquam eget neque turpis. Phasellus nibh ex, tristique a magna
                                ac, convallis tincidunt diam. Nulla facilisi. Phasellus porta sapien sit amet tortor
                                rhoncus mattis.</p>
                        </div>
                        <div class="button_fill intro_button"><a href="#">read more</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="milestones">
        <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/milestones.jpg' %}"
             data-speed="0.8"></div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="section_title light text-center"><h1>Fun Facts</h1></div>
                </div>
            </div>
            <div class="row milestones_row">

                <div class="col-xl-3 col-md-6">
                    <div class="milestone text-center">
                        <div class="milestone_content ml-auto mr-auto">
                            <div class="milestone_counter" data-end-value="55126">0</div>
                            <div class="milestone_icon"><img src="{% static 'images/alarm-clock.svg' %}"
                                                             alt="https://www.flaticon.com/authors/smashicons"></div>
                        </div>
                        <div class="milestone_title">Streamed Hours</div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="about">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="about_container d-flex flex-lg-row flex-column align-items-start justify-content-start">
                        <div class="about_content">
                            <div class="section_title"><h1>About Me</h1></div>
                            <div class="about_text">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a bibendum sem. Fusce
                                    dignissim et diam quis pretium. Etiam efficitur semper accumsan. Sed et dui aliquet,
                                    ultrices tellus non, sagittis magna. Nullam justo quam, vestibulum non magna et,
                                    tempus tincidunt est. Ut laoreet magna ac luctus lacinia. Aliquam eget neque turpis.
                                    Phasellus nibh ex, tristique a magna ac, convallis tincidunt diam. Nulla facilisi.
                                    Phasellus porta sapien sit amet tortor rhoncus mattis.</p>
                            </div>
                            <div class="social">
                                <ul class="d-flex flex-row align-items-start justify-content-start">
                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-soundcloud" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="about_image"><img src="{% static 'images/man.png' %}" alt></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="newsletter">
        <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/newsletter.jpg' %}"
             data-speed="0.8"></div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="section_title light text-center"><h1>Join my Newsletter</h1></div>
                    <div class="newsletter_text text-center">
                        <p>Stay on track with the latest information about our podcasts, guests, special guest and
                            giveaways.</p>
                    </div>
                </div>
            </div>
            <div class="row newsletter_row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="newsletter_form_container">
                        <form action="#"
                              class="newsletter_form d-flex flex-md-row flex-column align-items-md-start align-items-center justify-content-md-between justify-content-start"
                              id="newsletter_form">
                            <input type="email" class="newsletter_input" required="required">
                            <button class="newsletter_button button_fill">subscribe now!</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/contact_responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/contact.css' %}">
{% endblock links %}

{% block content %}

    <div class="home">
        <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="images/contact.jpg"
             data-speed="0.8"></div>
        <div class="home_container d-flex flex-column align-items-center justify-content-center">
            <div class="home_content">
                <div class="home_title"><h1>blog</h1></div>
            </div>
        </div>
    </div>

    <div class="contact">
        <div class="container">
            <div class="row">
                <div class="col">

                    <div class="intro">
                        <div class="section_title text-center"><h1>Get in touch</h1></div>
                        <div class="intro_text text-center">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a bibendum sem. Fusce
                                dignissim et diam quis pretium.
                                Etiam efficitur semper accumsan. Sed et dui aliquet, ultrices tellus non, sagittis
                                magna. Nullam justo quam, vestibulum non magna et, tempus tincidunt est. Ut laoreet
                                magna ac luctus lacinia. Aliquam eget neque turpis. Phasellus nibh ex, tristique a magna
                                ac, convallis tincidunt diam. Nulla facilisi. Phasellus porta sapien sit amet tortor
                                rhoncus mattis.</p>
                        </div>
                        <div class="button_fill intro_button text-center ml-auto mr-auto"><a href="#">read more</a>
                        </div>
                    </div>

                    <div class="contact_form_container">
                        <div class="contact_form_title text-center">Send a message</div>
                        <div class="row">
                            <div class="col-lg-8 offset-lg-2">
                                <form action="#" method="post" id="contact_form" class="contact_form">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-6 contact_col">
                                            {{ form.name }}
                                        </div>
                                        <div class="col-md-6">
                                            {{ form.phone }}
                                        </div>
                                    </div>
{#                                    <div><input type="text" class="contact_input" placeholder="Subject"></div>#}
                                    <div>{{ form.subject }}</div>

                                    <div>{{ form.message }}</div>

                                    <button class="contact_button button_fill ml-auto mr-auto">send</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="google_map_container">
                        <div class="map">
                            <div id="google_map" class="google_map">
                                <div class="map_container">
                                    <div id="map"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="newsletter">
        <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/blog_3.jpg' %}"
             data-speed="0.8"></div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="section_title light text-center"><h1>Join my Newsletter</h1></div>
                    <div class="newsletter_text text-center">
                        <p>Stay on track with the latest information about our podcasts, guests, special guest and
                            giveaways.</p>
                    </div>
                </div>
            </div>
            <div class="row newsletter_row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="newsletter_form_container">
                        <form action="#"
                              class="newsletter_form d-flex flex-md-row flex-column align-items-md-start align-items-center justify-content-md-between justify-content-start"
                              id="newsletter_form">
                            <input type="email" class="newsletter_input" required="required">
                            <button class="newsletter_button button_fill">subscribe now!</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/episodes.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/episodes.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/episodes_responsive.css' %}">
{% endblock links %}
{% block content %}


    <div class="home">
        <div class="parallax_background parallax-window" data-parallax="scroll"
             data-image-src="{% static 'images/about.jpg' %}"
             data-speed="0.8"></div>
        <div class="home_container d-flex flex-column align-items-center justify-content-center">
            <div class="home_content">
                <div class="home_title"><h1>episodes</h1></div>
            </div>
        </div>
    </div>

    <div class="episodes">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="season_links">
                        <ul class="d-flex flex-row align-items-start justify-content-center flex-wrap">
                            <li class="item_filter_btn" data-filter="*">All Seasons</li>
                            <li class="item_filter_btn" data-filter=".s1">Season 1</li>
                            <li class="item_filter_btn" data-filter=".s2">Season 2</li>
                            <li class="item_filter_btn" data-filter=".s3">Season 3</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row episodes_row">

                <div class="col-lg-3">
                    <div class="sidebar">

                        <div class="sidebar_search">
                            <div class="sidebar_title">Search</div>
                            <form action="#" class="search_form" id="search_form">
                                <input type="text" class="search_input" placeholder="Search here" required="required">
                                <button class="search_button"><img src="images/search.png" alt></button>
                            </form>
                        </div>

                        <div class="sidebar_list">
                            <div class="sidebar_title">Categories</div>
                            <ul>
                                {% for category in categories %}
                                    <li><a href="#">{{ category.category }}</a></li>
                                {% endfor %}

                            </ul>
                        </div>

                        <div class="sidebar_tags">
                            <div class="sidebar_title">Tags</div>
                            <div class="tags">
                                <ul class="d-flex flex-row align-items-start justify-content-start flex-wrap">
                                    {% for tag in tags %}
                                        <li><a href="#">{{ tag.tag }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>

                        <div class="sidebar_archive">
                            <div class="sidebar_title">Archive</div>
                            <div class="dropdown">
                                <ul>
                                    <li class="dropdown_selected d-flex flex-row align-items-center justify-content-start">
                                        <span>Choose archive</span><i class="fa fa-chevron-down ml-auto"
                                                                      aria-hidden="true"></i>
                                        <ul>
                                            {% for podcast in podcast_list %}
                                                <li><a href="#">{{ podcast.created|date:"M Y" }}</a></li>
                                            {% endfor %}

                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-9 episodes_col">
                    <div class="episodes_container">
                        {% for podcast in podcast_list %}
                            <div class="episode d-flex flex-row align-items-start justify-content-start s1">
                                <div>
                                    <div class="episode_image">
                                        <img src="{{ podcast.picture.url }}" alt>
                                        <div class="tags">
                                            <ul class="d-flex flex-row align-items-start justify-content-start">
                                                <li><a href="#">{{ podcast.tags.all.first }}</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="episode_content">
                                    <div class="episode_name"><a
                                            href="{% url 'episode' podcast.pk %}">{{ podcast.title }}</a></div>
                                    <div class="episode_date"><a href="#">{{ podcast.created|date:"d M, Y" }}</a></div>
                                    <div class="show_info d-flex flex-row align-items-start justify-content-start">
                                        <div class="show_fav d-flex flex-row align-items-center justify-content-start">
                                            <div class="show_fav_icon show_info_icon">
                                                <img class="svg" src="{% static 'images/heart.svg' %}" alt>
                                            </div>
                                            <div class="show_fav_count">{{ podcast.likes_set.count }} Likes</div>
                                        </div>
                                        <div class="show_comments">
                                            <a href="#">
                                                <div class="d-flex flex-row align-items-center justify-content-start">
                                                    <div class="show_comments_icon show_info_icon">
                                                        <img class="svg" src="{% static 'images/speech-bubble.svg' %}"
                                                             alt>
                                                    </div>
                                                    <div class="show_comments_count">{{ podcast.comments_set.count }}
                                                        Comments
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>

                                    <div class="single_player_container">
                                        <div class="single_player d-flex flex-row align-items-center justify-content-start">
                                            <div id="jplayer_1" class="jp-jplayer" style="width: 0px; height: 0px;"><img
                                                    id="jp_poster_0" style="width: 0px; height: 0px; display: none;">
                                                <audio id="jp_audio_0" preload="metadata"
                                                       src="{{ podcast.file.url }}"
                                                       title="Better Days"></audio>
                                            </div>
                                            <div id="jp_container_1" class="jp-audio" role="application"
                                                 aria-label="media player">
                                                <div class="jp-type-single">
                                                    <div class="player_controls">
                                                        <div class="jp-gui jp-interface d-flex flex-row align-items-center justify-content-start">
                                                            <div class="jp-controls-holder time_controls d-flex flex-row align-items-center justify-content-between">
                                                                <div>
                                                                    <div class="jp-controls-holder play_button ml-auto">
                                                                        <button class="jp-play" tabindex="0"></button>
                                                                    </div>
                                                                </div>
                                                                <div>
                                                                    <div class="jp-progress">
                                                                        <div class="jp-seek-bar" style="width: 100%;">
                                                                            <div class="jp-play-bar"
                                                                                 style="width: 0%;"></div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="jp-volume-controls d-flex flex-row align-items-center justify-content-between ml-auto">
                                                                <div class="d-flex flex-row align-items-center justify-content-start">
                                                                    <button class="jp-mute" tabindex="0"></button>
                                                                </div>
                                                                <div class="d-flex flex-row align-items-center justify-content-start">
                                                                    <div class="jp-volume-bar">
                                                                        <div class="jp-volume-bar-value"
                                                                             style="width: 20%;"></div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="jp-no-solution" style="display: none;">
                                                        <span>Update Required</span>
                                                        To play the media you will need to either update your browser to
                                                        a recent version or update your <a
                                                            href="http://get.adobe.com/flashplayer/" target="_blank">Flash
                                                        plugin</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
            <div class="row page_nav_row">
                <div class="col">
                    <div class="page_nav d-flex flex-row align-items-center justify-content-center">
                        <ul class="d-flex flex-row">
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}